### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by sergio91pt** [bpocallaghan/sluggable#1]
https://github.com/bpocallaghan/sluggable/blob/29b059985b196f6d326a4b37053d2219c68b8f70/src/HasSlug.php#L172

If the "slug name" is based on user input, since `$slug` is not properly escaped, it can be used for SQL injection. 
You should consider using the `where` method instead of `whereRaw`, or alternatively use the binding param.

**Comment by bpocallaghan** [comment]
Hi @sergio91pt 
Thanks for the feedback and information - I did not know that (was under the impression the raw queries also gets escaped - silly me)

I've changed it to the `where` method and published a new release v1.2.2.

Please shout if you notice anything else, thanks for consider using the package!
